name: Run Tests

on:
  push:
    branches:
      test

jobs:
  build:

    runs-on:
      ubuntu-latest

    environment: PROD

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install

    - name: Run tests
      run: pipenv run python -m unittest discover -s tests
      env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

